// Generated by delombok at Sat Jul 28 16:45:23 CEST 2018
package wf.frk.f3b.jme3.mergers;

import com.jme3.scene.Node;
import com.jme3.scene.Spatial;
import f3b.Datas.Data;
import f3b.Tobjects.TObject;
import wf.frk.f3b.jme3.F3bContext;

public class NodesMerger implements Merger {
	@Override
	public void apply(Data src, Node root, F3bContext context) {
		for (TObject n : src.getTobjectsList()) {
			String id = n.getId();
			Spatial child = (Spatial) context.get(id);
			if (child == null) {
				child = context.getSettings().getNodeBuilder().build(n.hasName() ? n.getName() : n.getId());
				root.attachChild(child);
				context.put(id, child);
			}
			child.setLocalRotation(wf.frk.f3b.jme3.ext.f3b.TypesExt.toJME(n.getRotation()));
			child.setLocalTranslation(wf.frk.f3b.jme3.ext.f3b.TypesExt.toJME(n.getTranslation()));
			child.setLocalScale(wf.frk.f3b.jme3.ext.f3b.TypesExt.toJME(n.getScale()));
		}
	}
}
