// Generated by delombok at Sat Jul 28 16:45:23 CEST 2018
package wf.frk.f3b.jme3.ext.jme3;

import java.lang.reflect.Field;

import wf.frk.f3banimation.AnimControl;
import wf.frk.f3banimation.Skeleton;

public class AnimControlExt {
	@java.lang.SuppressWarnings("all")
	private static final org.apache.logging.log4j.Logger log = org.apache.logging.log4j.LogManager.getLogger(AnimControlExt.class);

	public static void setSkeleton(AnimControl ac, Skeleton sk) {
		log.debug("Set skeleton {} to {}", sk, ac);
		Field field = null;
		// We can't rely on field name, or obfuscation will break the code.
		Field[] fields = AnimControl.class.getDeclaredFields();
		for (Field f : fields) {
			if (f.getType() == Skeleton.class) {
				field = f;
				break;
			}
		}
		if (field == null) {
			log.error("Something went bad, can\'t find Skeleton field in AnimControl.class!");
			return;
		}
		field.setAccessible(true);
		try {
			field.set(ac, sk);
		} catch (Exception e) {
			e.printStackTrace();
		}
		if (sk != null) sk.resetAndUpdate();
	}
}
