// Generated by delombok at Sat Jul 28 16:45:23 CEST 2018
package wf.frk.f3b.jme3.ext.jme3;

import com.jme3.light.DirectionalLight;
import com.jme3.light.Light;
import com.jme3.light.PointLight;
import com.jme3.light.SpotLight;
import com.jme3.math.Vector3f;

public class LightExt {
	@java.lang.SuppressWarnings("all")
	private static final org.apache.logging.log4j.Logger log = org.apache.logging.log4j.LogManager.getLogger(LightExt.class);

	public static void setPosition(Light light, Vector3f pos) {
		if (light instanceof PointLight) {
			if (!((PointLight) light).getPosition().equals(pos)) {
				((PointLight) light).setPosition(pos);
			}
		} else 
//				log.debug("Set position {} for light {}",pos,light);
		if (light instanceof SpotLight) {
			if (!((SpotLight) light).getPosition().equals(pos)) {
				((SpotLight) light).setPosition(pos);
			}
		}
//				log.debug("Set position {} for light {}",pos,light);
	}

	public static void setDirection(Light light, Vector3f dir) {
		if (light instanceof DirectionalLight) {
			if (!((DirectionalLight) light).getDirection().equals(dir)) {
				((DirectionalLight) light).setDirection(dir);
			}
		} else 
//				log.debug("Set direction {} for light {}",dir,light);
		if (light instanceof SpotLight) {
			if (!((SpotLight) light).getDirection().equals(dir)) {
				((SpotLight) light).setDirection(dir);
			}
		}
//				log.debug("Set direction {} for light {}",dir,light);
	}
}
