// Generated by delombok at Sat Jul 28 16:45:23 CEST 2018
package wf.frk.f3b.jme3.mergers.relations;

import com.jme3.scene.Node;
import f3b.Datas.Data;
import wf.frk.f3b.jme3.F3bContext;

public class RefData {
	public String ref1;
	public String ref2;
	public Data src;
	public Node root;
	public F3bContext context;

	@java.lang.SuppressWarnings("all")
	public RefData(final String ref1, final String ref2, final Data src, final Node root, final F3bContext context) {
		this.ref1 = ref1;
		this.ref2 = ref2;
		this.src = src;
		this.root = root;
		this.context = context;
	}
}
