// Generated by delombok at Sat Jul 28 16:45:23 CEST 2018
package wf.frk.f3b.jme3.scene;

import com.jme3.light.Light;
import com.jme3.math.Vector3f;
import com.jme3.renderer.RenderManager;
import com.jme3.renderer.ViewPort;
import com.jme3.scene.Spatial;
import com.jme3.scene.control.AbstractControl;

public class F3bLightControl extends AbstractControl {
	protected final Light light;

	@Override
	public void controlUpdate(float tpf) {
		if (spatial != null && light != null) {
			wf.frk.f3b.jme3.ext.jme3.LightExt.setPosition(light, spatial.getWorldTranslation());
			wf.frk.f3b.jme3.ext.jme3.LightExt.setDirection(light, spatial.getWorldRotation().mult(Vector3f.UNIT_Z));
		}
	}

//
//	Spatial debug;
	@Override
	public void setSpatial(Spatial sp) {
		super.setSpatial(sp);
//		debug=Debug.makeCube(0.4f,ColorRGBA.Red);
	}

	@Override
	protected void controlRender(RenderManager rm, ViewPort vp) {
	}

	@java.lang.SuppressWarnings("all")
	public F3bLightControl(final Light light) {
		this.light = light;
	}

	@java.lang.SuppressWarnings("all")
	public Light getLight() {
		return this.light;
	}
}
